# 1. ???? dev (????)
spring.profiles.active=dev

# 2. ???? (?????????????)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.app.jwtSecret=${JWT_SECRET}
spring.app.jwtExpirationMs=86400000