server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;

        #
        # 先找實體檔案，找不到就找資料夾，還是找不到就全部導向 /index.html
        try_files $uri $uri/ /index.html;
    }
}